version: "3.9"
services:
  strapi:
    container_name: energydashboard
    # build: .
    image: stefanofrontini/energydashboard:latest
    restart: always
    # env_file: .env
    # environment:
    #   DATABASE_CLIENT: ${DATABASE_CLIENT}
    #   DATABASE_HOST: strapiDB
    #   DATABASE_NAME: ${DATABASE_NAME}
    #   DATABASE_USERNAME: ${DATABASE_USERNAME}
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   JWT_SECRET: ${JWT_SECRET}
    #   ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
    #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    #   NODE_ENV: ${NODE_ENV}
    # volumes:
    #   - ./config:/opt/app/config
    #   - ./src:/opt/app/src
    #   - ./package.json:/opt/package.json
    #   - ./package-lock.json:/opt/package-lock.json
    #   - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      - main
    # depends_on:
    #   - postgres

  # strapiDB:
  #   image: postgres:latest
  #   container_name: strapiDB
  #   platform: linux/amd64
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   volumes:
  #     - strapi-data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - strapi


  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - strapi
  #   depends_on:
  #     - strapiDB

# volumes:
#     strapi-data:

networks:
  default:
    name: main
    external: true
