version: "3.9"
services:
  strapi:
    container_name: energydashboard
    # build: .
    image: stefanofrontini/energydashboard:latest
    restart: always
    env_file: .env
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: c7eaf02fcc48b77f2d3d97b6db455f42
      ADMIN_JWT_SECRET: 23ae9be6a77865ee6dd9ebb53f21117b
      JWT_SECRET: b5346c04-b318-40e9-9141-1a5291c4d133
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: energydashboard
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: example
      DATABASE_CLIENT: postgres

    # volumes:
    #   - ./config:/opt/app/config
    #   - ./src:/opt/app/src
    #   - ./package.json:/opt/package.json
    #   - ./package-lock.json:/opt/package-lock.json
    #   - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      - main
    # depends_on:
    #   - postgres

  # strapiDB:
  #   image: postgres:latest
  #   container_name: strapiDB
  #   platform: linux/amd64
  #   restart: unless-stopped
  #   env_file: .env
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   volumes:
  #     - strapi-data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - strapi

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - strapi
  #   depends_on:
  #     - strapiDB

# volumes:
#     strapi-data:

networks:
  default:
    name: main
    external: true
